services:
  - type: web
    name: voltrex-backend
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: VOLTREX_ENV
        value: production
      - key: VOLTREX_CORS_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
